// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcoTpxFiI2QlF7UzGvaTWZPKDU7LXfg3Y',
    appId: '1:928532847395:web:46085c22825644972c4a96',
    messagingSenderId: '928532847395',
    projectId: 'mairieaneho-22b51',
    authDomain: 'mairieaneho-22b51.firebaseapp.com',
    storageBucket: 'mairieaneho-22b51.firebasestorage.app',
    measurementId: 'G-H85YXYZYWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-1Yv3ENYtP0Ba22YsEycm2eATNlQA4w',
    appId: '1:928532847395:android:4263bb9b16ea4e1c2c4a96',
    messagingSenderId: '928532847395',
    projectId: 'mairieaneho-22b51',
    storageBucket: 'mairieaneho-22b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_7tvZZxYAVYp0KHhj0xUPdi6LdOYDKMk',
    appId: '1:928532847395:ios:baa065e1a52923252c4a96',
    messagingSenderId: '928532847395',
    projectId: 'mairieaneho-22b51',
    storageBucket: 'mairieaneho-22b51.firebasestorage.app',
    iosBundleId: 'com.example.mairieAneho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_7tvZZxYAVYp0KHhj0xUPdi6LdOYDKMk',
    appId: '1:928532847395:ios:baa065e1a52923252c4a96',
    messagingSenderId: '928532847395',
    projectId: 'mairieaneho-22b51',
    storageBucket: 'mairieaneho-22b51.firebasestorage.app',
    iosBundleId: 'com.example.mairieAneho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcoTpxFiI2QlF7UzGvaTWZPKDU7LXfg3Y',
    appId: '1:928532847395:web:aed2d82eba9a4c722c4a96',
    messagingSenderId: '928532847395',
    projectId: 'mairieaneho-22b51',
    authDomain: 'mairieaneho-22b51.firebaseapp.com',
    storageBucket: 'mairieaneho-22b51.firebasestorage.app',
    measurementId: 'G-RNFG72GGKY',
  );
}
